package urjc.grupoo.system.ui.Forms.clientForms.offerCreationForms;

import urjc.grupoo.system.ui.Forms.clientForms.offerCreationForms.buttons.ShowShipButton;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import urjc.grupoo.data.shipsData.Spaceship;
import urjc.grupoo.system.ui.SystemSession;

/**
 *
 * @author Gonzalo Ortega
 */
public class ShowShip extends javax.swing.JPanel {

    private final SystemSession session;
    private final Spaceship ship;
    private JPanel propulsionList;
    private JPanel defencesList;
    private JPanel weaponsList;
    private JPanel shipsList;

    /**
     * Creates new form SubsciptionsScreen
     *
     * @param session
     * @param ship
     */
    public ShowShip(SystemSession session, Spaceship ship) {
        this.session = session;
        this.ship = ship;
        initComponents();

        shipTypeField.setText(ship.getType());
        registerField.setText(ship.getRegisterNumber());
        maxSpeedField.setText(Double.toString(ship.getSecondpropulsion().getMaxSpeed()));
        crewNumberField.setText(Integer.toString(ship.getCrewMembersAmount()));
        pasangerNumberField.setText(Integer.toString(ship.getPassengersLimit()));
        maxCargoField.setText(Integer.toString(ship.getMaxCargo()));
        addPropulsions();
        addDefences();
        if (ship.getWeaponList() != null) {
            addWeapons();
        }
        if (ship.getSpaceshipList() != null) {
            addShips();
        }
    }

    private void addPropulsions() {
        propulsionList = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        propulsionList.add(new JPanel(), gbc);
        propulsionPanel.setViewportView(propulsionList);

        addEntry(ship.getFirstpropulsion().getName(), propulsionList);
        addEntry(ship.getSecondpropulsion().getName(), propulsionList);
    }

    private void addDefences() {
        defencesList = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        defencesList.add(new JPanel(), gbc);
        defencesPanel.setViewportView(defencesList);

        ship.getDefenceList().forEach((defence) -> {
            addEntry(defence.getDefenceType(), defencesList);
        });
    }

    private void addWeapons() {
        weaponsList = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        weaponsList.add(new JPanel(), gbc);
        weaponsPanel.setViewportView(weaponsList);
        ship.getWeaponList().forEach((weapon) -> {
            addEntry(weapon.getName() + " " + weapon.getPower() + " " + "GJ", weaponsList);
        });
    }

    private void addShips() {
        shipsList = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        shipsList.add(new JPanel(), gbc);
        shipsPanel.setViewportView(shipsList);

        ship.getSpaceshipList().forEach((ship) -> {
            addEntry(ship.getType(), shipsList);
            addButton(ship, shipsList);
        });
    }

    private void addButton(Spaceship ship, JPanel displayList) {
        JPanel panel = new JPanel();
        panel.add(new ShowShipButton(session, ship));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        displayList.add(panel, gbc, 0);
    }

    private void addEntry(String text, JPanel displayList) {
        JPanel panel = new JPanel();
        panel.add(new JLabel(text));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        displayList.add(panel, gbc, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerField = new javax.swing.JTextField();
        registerLabel1 = new javax.swing.JLabel();
        tripulantsLabel = new javax.swing.JLabel();
        crewNumberField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        propulsionLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        maxSpeedField = new javax.swing.JTextField();
        propulsionLabel1 = new javax.swing.JLabel();
        propulsionLabel2 = new javax.swing.JLabel();
        shipTypeField = new javax.swing.JTextField();
        pasangerNumberField = new javax.swing.JTextField();
        tripulantsLabel1 = new javax.swing.JLabel();
        maxCargoField = new javax.swing.JTextField();
        tripulantsLabel2 = new javax.swing.JLabel();
        propulsionLabel3 = new javax.swing.JLabel();
        weaponsPanel = new javax.swing.JScrollPane();
        propulsionPanel = new javax.swing.JScrollPane();
        defencesPanel = new javax.swing.JScrollPane();
        shipsPanel = new javax.swing.JScrollPane();

        registerField.setEditable(false);

        registerLabel1.setText("Velocidad sublumínica máxima:");

        tripulantsLabel.setText("Número de tripulantes:");

        crewNumberField.setEditable(false);

        nameLabel.setText("Tipo de nave:");

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        propulsionLabel.setText("Tipos de propulsión:");

        registerLabel.setText("Número de registro:");

        maxSpeedField.setEditable(false);

        propulsionLabel1.setText("Defensas:");

        propulsionLabel2.setText("Armas:");

        shipTypeField.setEditable(false);

        pasangerNumberField.setEditable(false);

        tripulantsLabel1.setText("Número de pasajeros:");

        maxCargoField.setEditable(false);

        tripulantsLabel2.setText("Capacidad de carga:");

        propulsionLabel3.setText("Naves en su interior:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(propulsionPanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(propulsionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(propulsionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shipsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(propulsionLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(propulsionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 222, Short.MAX_VALUE))
                                    .addComponent(weaponsPanel))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shipTypeField)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(backButton)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tripulantsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(registerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxSpeedField)
                                    .addComponent(crewNumberField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tripulantsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tripulantsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pasangerNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addComponent(maxCargoField))))
                        .addContainerGap(419, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(registerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shipTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLabel1)
                    .addComponent(maxSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripulantsLabel)
                    .addComponent(crewNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripulantsLabel1)
                    .addComponent(pasangerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripulantsLabel2)
                    .addComponent(maxCargoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propulsionLabel)
                    .addComponent(propulsionLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propulsionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propulsionLabel3)
                    .addComponent(propulsionLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        session.getController().goBack();
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField crewNumberField;
    private javax.swing.JScrollPane defencesPanel;
    private javax.swing.JTextField maxCargoField;
    private javax.swing.JTextField maxSpeedField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pasangerNumberField;
    private javax.swing.JLabel propulsionLabel;
    private javax.swing.JLabel propulsionLabel1;
    private javax.swing.JLabel propulsionLabel2;
    private javax.swing.JLabel propulsionLabel3;
    private javax.swing.JScrollPane propulsionPanel;
    private javax.swing.JTextField registerField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerLabel1;
    private javax.swing.JTextField shipTypeField;
    private javax.swing.JScrollPane shipsPanel;
    private javax.swing.JLabel tripulantsLabel;
    private javax.swing.JLabel tripulantsLabel1;
    private javax.swing.JLabel tripulantsLabel2;
    private javax.swing.JScrollPane weaponsPanel;
    // End of variables declaration//GEN-END:variables

}
